/**
 * pi CLI credential check infrastructure.
 *
 * Runs `pi -p --mode json` as a subprocess with the user's credential.
 * Provides:
 *   - `runCredentialCliCheck(cred)`: runs the CLI, returns raw parsed events.
 *     Used by both `runL4Check` (L4-specific assertion) and
 *     `runPiDiagnostics` (four-in-one L1-L4 assertion).
 *   - `runL4Check(input)`: backward-compat wrapper for the L4 agent circuit.
 *
 * Design: docs/vulnhunt-srv/architecture/unified-credential-models-json-v1.0.md §3.2
 *
 * models.json is generated by `buildModelsJson` (credential-models.ts) and
 * placed at `<workDir>/agent/models.json`. pi is pointed there via
 * `PI_CODING_AGENT_DIR` env (pi CLI reads models.json by convention).
 */

import { spawn } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PI_VERSION } from "@vulnhunter/shared";
import { logger } from "../../infra/logger.js";
import { formatRawError } from "./pi-diagnostics.js";
import {
  buildModelsJson,
  type DecryptedCredentialLike,
} from "./credential-models.js";

// ── Types ─────────────────────────────────────────────────────────────

export interface L4CheckInput {
  baseUrl: string;
  apiKey: string;
  modelId: string;
  protoType: string;
  thinkingEffort?: string;
  /** Abort signal for cancellation. */
  signal?: AbortSignal;
}

export type L4CheckResult = {
  status: "pass" | "fail";
  durationMs: number;
  detail: string;
  /** Raw JSON events from pi CLI (truncated for diagnostics). */
  events?: unknown[];
};

/**
 * Raw output from a pi CLI credential check run.
 * Consumers (L4 wrapper, four-in-one diagnostics) derive their own
 * layer-specific assertions from these events.
 */
export interface CredentialCliResult {
  /** Parsed JSON events from pi `--mode json` stdout (JSONL). */
  events: unknown[];
  /** Raw stderr output. */
  stderr: string;
  /** True when the hard 120s deadline fired. */
  timedOut: boolean;
  /** Wall-clock duration in ms. */
  durationMs: number;
}

// ── Constants ─────────────────────────────────────────────────────────

/** fish 2026-08-06: L1-L4 unified 120s timeout. */
export const CLI_TIMEOUT_MS = 120_000;

/**
 * Diagnostic prompt (fish 2026-08-08): exercises all four layers with a
 * read-only tool call + a question that triggers thinking (prime check).
 * A canary file is pre-placed in the work directory.
 */
const CANARY_FILENAME = "diagnostic-canary.txt";
const CANARY_CONTENT = "VHN-DIAG-CANARY-9F3A";
const DIAGNOSTIC_PROMPT = `First, use the read tool to read ${CANARY_FILENAME}. Then answer: is 29 a prime number? Reply with the file content followed by yes or no.`;

/** Built-in thinking levels that pi accepts via model suffix `:level`. */
const BUILTIN_THINKING_LEVELS = ["off", "minimal", "low", "medium", "high", "xhigh", "max"];

/** Read-only tools for diagnostic (fish 2026-08-08: no bash/edit/write —
 *  upstream tampering cannot execute commands or write files). */
const DIAGNOSTIC_TOOLS = "read,ls,grep,find";

// ── models.json writer (delegates to unified module) ──────────────────

async function writeModelsJsonFromCredential(
  agentDir: string,
  cred: DecryptedCredentialLike,
): Promise<Record<string, string>> {
  const result = await buildModelsJson(cred);
  await mkdir(agentDir, { recursive: true });
  await writeFile(join(agentDir, "models.json"), JSON.stringify(result.modelsJson, null, 2) + "\n", "utf-8");
  return result.childEnv;
}

// ── CLI runner ─────────────────────────────────────────────────────────

/**
 * Run pi CLI headless with the given credential and return parsed events.
 *
 * The models.json is generated by `buildModelsJson` (unified module), placed
 * at `<workDir>/agent/models.json`, and pi is pointed there via
 * `PI_CODING_AGENT_DIR`. The API key rides the env channel ($ENV_VAR template
 * in models.json), never on argv.
 *
 * Timeout: 120s hard deadline with SIGTERM → SIGKILL → forceSettle.
 * The returned promise ALWAYS resolves (a hung subprocess cannot leave
 * the caller spinning).
 */
export async function runCredentialCliCheck(
  cred: DecryptedCredentialLike,
  opts?: {
    signal?: AbortSignal;
    /** Called for each parsed JSONL event as it arrives (progressive diagnostics). */
    onEvent?: (event: unknown) => void;
  },
): Promise<CredentialCliResult> {
  const start = Date.now();
  let workDir: string | null = null;

  try {
    workDir = await mkdtemp(join(tmpdir(), "pi-cli-"));
    const agentDir = join(workDir, "agent");
    const childEnvExtra = await writeModelsJsonFromCredential(agentDir, cred);

    // Pre-place canary file in workDir (read tool reads from cwd)
    await writeFile(join(workDir, CANARY_FILENAME), CANARY_CONTENT + "\n", "utf-8");

    // Build args: pi CLI with read-only tools
    // fish 2026-08-08: thinking level via model suffix (VulnForge same pattern:
    // --model "<id>:<level>" — pi model-resolver parses the suffix).
    const effort = cred.thinking_effort?.toLowerCase() ?? "";
    const isBuiltinLevel = BUILTIN_THINKING_LEVELS.includes(effort);
    if (effort && !isBuiltinLevel) {
      logger.warn({ effort }, "Non-builtin thinking level — model suffix omitted");
    }
    const modelArg = (isBuiltinLevel && effort !== "off")
      ? `${cred.model_id}:${effort}`
      : cred.model_id;

    const args = [
      "-p",
      "--mode", "json",
      "--no-session",
      "--provider", "platform",
      "--model", modelArg,
      // fish 2026-08-08: read-only tool surface — no bash/edit/write.
      "--tools", DIAGNOSTIC_TOOLS,
      DIAGNOSTIC_PROMPT,
    ];

    const events: unknown[] = [];
    let stderr = "";
    let timedOut = false;

    await new Promise<void>((resolve) => {
      const child = spawn("pi", args, {
        cwd: workDir!,
        env: {
          ...process.env,
          PI_CODING_AGENT_DIR: agentDir,
          ...childEnvExtra,
        },
        stdio: ["ignore", "pipe", "pipe"],
      });

      let settled = false;
      const forceSettle = () => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        resolve();
      };

      // Hard deadline (fish 2026-08-06): when it fires, the layer FAILS.
      // SIGTERM is best-effort; SIGKILL after a 2s grace for orphan cleanup.
      // forceSettle() guarantees the promise ALWAYS resolves — a hung
      // subprocess can no longer leave the credential test spinning.
      const timer = setTimeout(() => {
        timedOut = true;
        try { child.kill("SIGTERM"); } catch { /* already dead */ }
        setTimeout(() => {
          try { child.kill("SIGKILL"); } catch { /* already dead */ }
        }, 2_000);
        forceSettle();
      }, CLI_TIMEOUT_MS);

      opts?.signal?.addEventListener("abort", () => {
        try { child.kill("SIGTERM"); } catch { /* already dead */ }
        forceSettle();
      }, { once: true });

      let stdoutBuf = "";
      child.stdout.on("data", (chunk: Buffer) => {
        stdoutBuf += chunk.toString();
        const lines = stdoutBuf.split("\n");
        stdoutBuf = lines.pop() ?? "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed || trimmed.startsWith("Warning:")) continue;
          try {
            const ev = JSON.parse(trimmed);
            events.push(ev);
            try { opts?.onEvent?.(ev); } catch { /* emitter must not kill the stream */ }
          } catch {
            // Non-JSON line — skip
          }
        }
      });

      child.stderr.on("data", (chunk: Buffer) => {
        stderr += chunk.toString();
      });

      child.on("close", () => {
        if (!settled) {
          // Parse any remaining stdout
          if (stdoutBuf.trim()) {
            try { events.push(JSON.parse(stdoutBuf.trim())); } catch { /* skip */ }
          }
          forceSettle();
        }
      });

      // Early exit on non-zero exit code (ENOENT, bad args, etc.)
      child.on("exit", (code) => {
        if (!settled && code !== 0 && code !== null) {
          if (stdoutBuf.trim()) {
            try { events.push(JSON.parse(stdoutBuf.trim())); } catch { /* skip */ }
          }
          forceSettle();
        }
      });

      child.on("error", () => {
        if (!settled) forceSettle();
      });
    });

    const durationMs = Date.now() - start;
    return { events, stderr, timedOut, durationMs };
  } catch (err) {
    const durationMs = Date.now() - start;
    const msg = err instanceof Error ? err.message : String(err);
    logger.warn({ err: msg, durationMs }, "credential CLI check failed");
    return { events: [], stderr: msg, timedOut: false, durationMs };
  } finally {
    if (workDir) {
      await rm(workDir, { recursive: true, force: true }).catch(() => {});
    }
  }
}

// ── L4 backward-compat wrapper ────────────────────────────────────────

/**
 * L4 check: spawn pi CLI, assert the agent closed a real tool loop.
 *
 * This is the original L4 entry point. It now delegates to
 * `runCredentialCliCheck` and applies L4-specific assertions.
 * `runPiDiagnostics` (four-in-one) also uses the same CLI run.
 */
export async function runL4Check(input: L4CheckInput): Promise<L4CheckResult> {
  const cred: DecryptedCredentialLike = {
    proto_type: input.protoType,
    base_url: input.baseUrl,
    model_id: input.modelId,
    thinking_effort: input.thinkingEffort ?? "off",
    context_window_tokens: 128_000, // L4CheckInput doesn't carry this; CLI uses catalog fallback
    api_key: input.apiKey,
  };

  const { events, stderr, timedOut, durationMs } = await runCredentialCliCheck(cred, { signal: input.signal });

  // Hard timeout verdict
  if (timedOut) {
    return {
      status: "fail" as const,
      durationMs,
      detail: formatRawError(`timeout after ${CLI_TIMEOUT_MS / 1000}s`),
    };
  }

  // Assert: agent must close a real tool loop
  const agentSettled = events.some(
    (e) => (e as { type?: string }).type === "agent_settled",
  );

  const readToolCalls = events.filter((e) => {
    const ev = e as { type?: string; message?: { content?: Array<{ type?: string; name?: string }> } };
    return ev.type === "message_end" && Array.isArray(ev.message?.content)
      && ev.message!.content!.some((b) => b.type === "toolCall" && b.name === "read");
  });
  const readToolResults = events.filter((e) => {
    const ev = e as { type?: string; toolResults?: Array<{ toolName?: string; content?: unknown[] }> };
    return ev.type === "turn_end" && Array.isArray(ev.toolResults)
      && ev.toolResults!.some((r) => r.toolName === "read" && Array.isArray(r.content) && r.content.length > 0);
  });
  const toolCallObserved = readToolCalls.length > 0 && readToolResults.length > 0;

  const assistantMessages = events.filter(
    (e) =>
      (e as { type?: string }).type === "message_end" &&
      (e as { message?: { role?: string } }).message?.role === "assistant",
  );

  const hasError = assistantMessages.some(
    (e) => (e as { message?: { stopReason?: string } }).message?.stopReason === "error",
  );

  const hasContent = assistantMessages.some((e) => {
    const content = (e as { message?: { content?: unknown[] } }).message?.content;
    return Array.isArray(content) && content.length > 0;
  });

  if (!agentSettled && events.length === 0) {
    return {
      status: "fail",
      durationMs,
      detail: stderr.trim().slice(0, 300) || "pi CLI produced no output",
    };
  }

  if (!agentSettled) {
    return {
      status: "fail",
      durationMs,
      detail: "pi CLI did not reach agent_settled state",
      events: events.slice(0, 5),
    };
  }

  if (hasError) {
    const errMsg = assistantMessages.find(
      (e) => (e as { message?: { errorMessage?: string } }).message?.errorMessage,
    );
    const detail =
      (errMsg as { message?: { errorMessage?: string } })?.message?.errorMessage ??
      "upstream error";
    return {
      status: "fail",
      durationMs,
      detail: detail.slice(0, 300),
      events: events.slice(0, 5),
    };
  }

  if (!hasContent) {
    return {
      status: "fail",
      durationMs,
      detail: "Agent completed but produced no output content",
      events: events.slice(0, 5),
    };
  }

  if (!toolCallObserved) {
    return {
      status: "fail",
      durationMs,
      detail: `Agent completed without a clean read tool call (read_calls=${readToolCalls.length}, read_results=${readToolResults.length}) — the model may not honor tool instructions or the endpoint rejects tool requests`,
      events: events.slice(0, 5),
    };
  }

  return {
    status: "pass",
    durationMs,
    detail: `Agent circuit OK (pi ${PI_VERSION}, read tool call + result verified, ${assistantMessages.length} assistant message(s))`,
  };
}
